CHANGELOG.md, __tests__/clients/inworld.client.spec.ts, __tests__/services/inworld_connection.service.spec.ts, examples/chat/src/app/chat/Chat.tsx, src/common/interfaces.ts, src/services/connection.service.ts, src/services/inworld_connection.service.ts
If `sendAudioSessionStart` is called twice in a row, the server produces an error (without providing any details to the user)
It should be checked on the client side
=> Prevent starting/ending the audio session two times in a row

CHANGELOG.md, __tests__/connection/web-socket.connection.spec.ts, __tests__/helpers.ts, src/components/sound/grpc_audio.playback.ts, src/connection/web-socket.connection.ts, src/services/connection.service.ts
* Send TextEvent before CancelResponses on text interruption
* Continue audio playing after interruption in Safari. Ended event is not triggered for audioBufferSourceNode in Safari after disconnect. And anyway it's not correct to call onEnded callback if track was stopped: onAfterPlaying should not be called in this case. That's why we need to remove this listener and make all required actions manually after stop
=> Fix interruptions

CHANGELOG.md, __tests__/clients/inworld.client.spec.ts, __tests__/components/history.spec.ts, __tests__/components/sound/grpc_audio.playback.spec.ts, __tests__/connection/web-socket.connection.spec.ts, __tests__/data_structures.ts, __tests__/entities/inworld_packet.entity.spec.ts, __tests__/factories/event.spec.ts, __tests__/helpers.ts, __tests__/services/connection.service.spec.ts, __tests__/services/inworld_connection.service.spec.ts, examples/chat/src/App.tsx, jest.config.json, src/clients/inworld.client.ts, src/common/data_structures.ts, src/common/helpers.ts, src/components/history.ts, src/components/sound/grpc_audio.playback.ts, src/components/sound/player.ts, src/connection/web-socket.connection.ts, src/entities/inworld_packet.entity.ts, src/factories/event.ts, src/index.ts, src/services/connection.service.ts, src/services/inworld_connection.service.ts, src/services/world_engine.service.ts
If you need to extend Inworld packet:
```
interface ExtendedCapabilities extends Capabilities {
newCapability: boolean;
}
interface NewEvent {
property?: string;
};
interface ExtendedInworldPacket extends InworldPacket {
newEvent: NewEvent;
}
const client = new InworldClient<
ExtendedCapabilities,
ExtendedInworldPacket
>()
...
.setConfiguration({
capabilities: { audio: true, newCapability: true }
})
.setExtension({
convertPacketFromProto: (proto: ProtoPacket) => {
const packet = InworldPacket.fromProto(
proto,
) as ExtendedInworldPacket;
packet.newEvent = {
property: v4(),
};
return packet;
},
// Any props except props that can be set using DSL (i.e. we exclude user/client/capabilities/name)
loadSceneProps: {}
});
```
If you don't need to extend Inworld packet do nothing additionally:
``` …
```
=> Allow to extend packets

CHANGELOG.md, __tests__/services/pb/world_engine.service.spec.ts, examples/chat/src/app/connection.ts, src/services/pb/world_engine.service.ts
- Ensure `beforeLoadScene` and `afterLoadScene` are present before call them
=> Release 1.5.3

.github/workflows/release.yml
Revert back `GITHUB_TOKEN` for `release:bump` command. Release is created automatically with this env variable
=> fix: Fix auto release creation

CHANGELOG.md, __tests__/connection/web-socket.connection.spec.ts, src/connection/web-socket.connection.ts
Fix "typo": proto packet should be generated once. And then to be converted to Inworld packet
https://inworldai.atlassian.net/browse/CORE-3622
=> Generate proto packet just once to dispatching it to the WebSocket connection

CHANGELOG.md, __tests__/factories/event.spec.ts, src/factories/event.ts
Add `correlationId`
https://inworldai.atlassian.net/browse/CORE-3622
=> feat: Add `correlationId` to text, custom and cancel response packets

CHANGELOG.md, src/components/history.ts
- Include overlooked calls to the `historyItem` method for queued packets
https://inworldai.atlassian.net/browse/CORE-3871
=> Include overlooked calls to the `historyItem` method for queued packets

CHANGELOG.md, __tests__/components/history.spec.ts, src/components/history.ts
Trigger parameter should be available in history item
https://inworldai.atlassian.net/browse/CORE-3947
=> fix: Include overlooked trigger parameters to corresponding history item

CHANGELOG.md, src/clients/inworld.client.ts, src/common/data_structures.ts, src/connection/web-socket.connection.ts, src/services/connection.service.ts
We should have opportunity to use async callbacks when it's required
https://inworldai.atlassian.net/browse/CORE-3888
=> Allow to use async `onDisconnect` and `onError`

CHANGELOG.md, __tests__/components/history.spec.ts, __tests__/entities/inworld_packet.entity.spec.ts, __tests__/services/connection.service.spec.ts, src/clients/inworld.client.ts, src/common/data_structures.ts, src/components/history.ts, src/connection/web-socket.connection.ts, src/entities/inworld_packet.entity.ts, src/services/connection.service.ts
- Allow to use async `onDisconnect` and `onError`
- Include the correlationId in both the fromProto conversion method and the associated historical items
- Include overlooked trigger parameters to corresponding history item
=> Release 1.6.2

CHANGELOG.md, __tests__/connection/web-socket.connection.spec.ts, __tests__/services/connection.service.spec.ts, src/common/data_structures.ts, src/connection/web-socket.connection.ts, src/services/connection.service.ts, src/services/inworld_connection.service.ts
Send a `MUTE` event when auto-reconnecting prior to transmitting any other packets, provided that a `MUTE` event was sent prior to the disconnection
https://inworldai.atlassian.net/browse/CORE-4030
=> fix: Send a `MUTE` event when auto-reconnecting prior to transmitting any other packets

CHANGELOG.md, __tests__/clients/inworld.client.spec.ts, __tests__/services/connection.service.spec.ts, src/common/data_structures.ts, src/services/connection.service.ts
Allow to add packets to history SDK object using configuration
https://inworldai.atlassian.net/browse/CORE-4031
=> Allow to add previous state packets to history

CHANGELOG.md, __tests__/clients/inworld.client.spec.ts, __tests__/connection/web-socket.connection.spec.ts, __tests__/services/connection.service.spec.ts, src/common/data_structures.ts, src/connection/web-socket.connection.ts, src/services/connection.service.ts, src/services/inworld_connection.service.ts
- Allow to add previous state packets to history
- Send a `MUTE` event when auto-reconnecting prior to transmitting any other packets, provided that a `MUTE` event was sent prior to the disconnection
=> Release 1.7.0

CHANGELOG.md, __tests__/clients/inworld.client.spec.ts, __tests__/services/connection.service.spec.ts, src/clients/inworld.client.ts, src/services/connection.service.ts
Add `onInterruption` callback to DSL
https://inworldai.atlassian.net/browse/CORE-4083
=> Expose `interactionId` and `utteranceId` of interrupted packets

examples/chat/package.json, examples/chat/yarn.lock
React app example (chat) checks eslint rules by default
And it works incorrectly in case of nesting dependencies. I.e. if only install chat dependencies without root repo dependencies. So if you just want to clone repo source code and run example it doesn’t work, you need to install root dependencies too.
Let’s skip eslint checks on example running. It will be checked on commit/PR anyway
https://inworldai.atlassian.net/browse/CORE-4170
=> Run chat example without eslint checking

CHANGELOG.md, __tests__/services/inworld_connection.service.spec.ts, src/services/inworld_connection.service.ts
It doesn't make a sense to call `player.stop` and `recorder.stop` manually
https://inworldai.atlassian.net/browse/CORE-4297
=> fix: Stop playing and recording sound on connection manual closing

examples/chat/package.json, examples/chat/yarn.lock, examples/generate_token/package.json, examples/generate_token/yarn.lock
Need to have DISABLE_ESLINT_PLUGIN=true for chat example, but it didn't work on Windows
https://inworldai.atlassian.net/browse/CORE-4338
=> fix: Set up environment variables for example package.json scripts in a cross-browser compatible manner

examples/chat/bak.env copy.local, examples/chat/bak.env.development.v2, examples/chat/src/app/components/3dAvatar/Lipsync.tsx, examples/chat/src/app/components/3dAvatar/Model.tsx
This fixes a bug in WebSDK example Chat  with a change in mesh id's due to updating Three.js. This fix changes the targets from id based to the mesh name itself to prevent this issue from occurring again.
https://inworldai.atlassian.net/browse/CORE-4365
=> Fix: WebSDK chat example. Bug with RPM Avatar default model naming target

packages/web-core/.npmignore, packages/web-core/CHANGELOG.md, packages/web-core/package.json, packages/web-core/replacers/json.cjs, packages/web-core/tsconfig.json, yarn.lock
Need to use JS file instead of JSON(package.json) to combine all files correctly in one CDN file. 
https://inworldai.atlassian.net/browse/INTG-887
https://github.com/inworld-ai/inworld-web-sdk/issues/100
=> fix: Use the JS built file instead of the JSON one to determine the current package version

.github/workflows/release.yml, README_DEV.md, packages/web-core/package.json, packages/web-threejs/package.json
Yarn command for workspaces produces additional outputs (even with silence flag).
So it doesn't work for GitHub actions eval
That's why yarn commands were replaced by GitHub runs
=> fix: Fix release notifications

packages/web-core/CHANGELOG.md, packages/web-core/src/services/connection.service.ts
Propagate missed user object to history
=> fix: Fix replacing player placeholder for narrated actions inside history

examples/chat/src/App.tsx, examples/chat/src/app/chat/AdditionalActions.tsx, examples/chat/src/app/chat/Chat.tsx, examples/chat/src/app/chat/History.tsx, examples/chat/src/app/configuration/ConfigView.tsx, examples/chat/src/app/types.ts
!!! NOT PUBLISHED FEATURE
NEED TO TEST USING INSTRUCTIONS FROM TESTME.md
- Add new chat mode to settings page (multi agents)
- Allow to chat with both characters
- Allow to overhear characters (call next turn trigger)
https://inworldai.atlassian.net/browse/INTG-931
=> feat: Add multi agent feature to chat example

examples/innequin-react/package.json, examples/innequin-react/yarn.lock, examples/rpm-react/package.json, examples/rpm-react/yarn.lock
Rolling back the web-sdk version for the Three.js react example projects as changes are needed for multi-agent.
=> fix: rolled back web-sdk to 2.2.0 for three.js examples

examples/chat/src/app/components/innequin/animator/facial/Eye.tsx, packages/web-core/__tests__/entities/scene.entity.spec.ts, packages/web-core/src/components/history.ts, packages/web-core/src/connection/web-socket.connection.ts, packages/web-core/src/entities/continuation/previous_dialog.entity.ts, packages/web-core/src/entities/packets/audio.entity.ts, packages/web-core/src/entities/scene.entity.ts, packages/web-core/src/factories/event.ts, packages/web-core/src/services/connection.service.ts, packages/web-threejs/src/innequin/animator/facial/InnequinEyes.ts
Otherwise we can an error:
Failed to execute 'addIceCandidate' on 'RTCPeerConnection': The remote description was null
https://github.com/inworld-ai/inworld-studio-fe/pull/1076
=> fix: Start WebRTC session directly after WebSocket opening

packages/web-core/CHANGELOG.md, packages/web-core/src/common/data_structures.ts, packages/web-core/src/connection/web-socket.connection.ts, packages/web-core/src/services/connection.service.ts, packages/web-core/src/services/inworld_connection.service.ts
- Await for CLOSED WebSocket connection state after CLOSING one
- Allow to change scene user parameters
https://inworldai.atlassian.net/browse/INTG-1879
https://inworldai.atlassian.net/browse/INTG-1880
=> feat: Make connection close method to be asynchronous

packages/web-core/CHANGELOG.md, packages/web-core/__tests__/connection/web-socket.connection.spec.ts, packages/web-core/__tests__/factories/event.spec.ts, packages/web-core/__tests__/services/entity.service.spec.ts, packages/web-core/__tests__/services/inworld_connection.service.spec.ts, packages/web-core/package.json, packages/web-core/src/common/data_structures.ts, packages/web-core/src/connection/web-socket.connection.ts, packages/web-core/src/factories/event.ts, packages/web-core/src/services/connection.service.ts, packages/web-core/src/services/conversation.service.ts, packages/web-core/src/services/entity.service.ts, packages/web-core/src/services/inworld_connection.service.ts, packages/web-core/src/zod/schema.ts, yarn.lock
When validateData property is set as true and sent packet has a wrong format (based on ts files generated from proto), you will see a warn on browser console with details what's wrong
https://inworldai.atlassian.net/browse/INTG-2151
=> feat: Allow to validate sent packets using zod

.github/workflows/reviewdog.yml, package.json, packages/web-core/__tests__/components/history.spec.ts, packages/web-core/__tests__/helpers/extension.ts, packages/web-core/__tests__/services/connection.service.spec.ts, packages/web-core/__tests__/services/inworld_connection.service.spec.ts, packages/web-core/__tests__/services/session_state.service.spec.ts, packages/web-core/package.json, packages/web-core/src/clients/inworld.client.ts, packages/web-core/src/common/data_structures/extension.ts, packages/web-core/src/common/data_structures/history.ts, packages/web-core/src/common/data_structures/index.ts, packages/web-core/src/components/history.ts, packages/web-core/src/connection/web-socket.connection.ts, packages/web-core/src/index.ts, packages/web-core/src/services/connection.service.ts, packages/web-core/src/services/conversation.service.ts, packages/web-core/src/services/session_state.service.ts, packages/web-threejs/package.json, yarn.lock
https://inworldai.atlassian.net/browse/INTG-2295
=> chore: Add GA to check circular deps

packages/web-core/package.json, packages/web-core/src/common/helpers.ts
Grpc gateway accept latency as a string only
Otherwise it returns an error
Reverted to previous behaviour
=> fix: Revert to previous format of latency as a string
