- CHANGELOG.md
- __tests__/clients/inworld.client.spec.ts
- __tests__/services/inworld_connection.service.spec.ts
- examples/chat/src/app/chat/Chat.tsx
- package.json
- src/common/interfaces.ts
- src/services/connection.service.ts
- src/services/inworld_connection.service.ts
* Improve chat example UI: add validation and rename fields
* Add narrated actions support
* Prevent starting/ending the audio session two times in a row
> Release 0.9.7

- CHANGELOG.md
- __tests__/components/sound/grpc_audio.playback.spec.ts
- __tests__/factories/event.spec.ts
- __tests__/services/connection.service.spec.ts
- __tests__/services/inworld_connection.service.spec.ts
- src/entities/inworld_packet.entity.ts
- src/factories/event.ts
- src/index.ts
- src/services/connection.service.ts
- src/services/inworld_connection.service.ts
`connection.sendTrigger('name', [{ name: 'p_name1', value: 'p_value1' }]);`
> Add parameters to triggers

- .eslintrc.json
- CHANGELOG.md
- __tests__/clients/inworld.client.spec.ts
- __tests__/components/history.spec.ts
- __tests__/components/sound/grpc_audio.playback.spec.ts
- __tests__/entities/emotion-behavior.entity.spec.ts
- __tests__/entities/emotion-strength.entity.spec.ts
- __tests__/factories/event.spec.ts
- __tests__/services/connection.service.spec.ts
- __tests__/services/inworld_connection.service.spec.ts
- examples/chat/src/app/chat/Chat.styled.ts
- examples/chat/src/app/chat/History.tsx
- examples/chat/src/app/components/CircularRpmAvatar.tsx
- package.json
- src/common/constants.ts
- src/components/history.ts
- src/entities/emotion-behavior.entity.ts
- src/entities/emotion-strength.entity.ts
- src/entities/inworld_packet.entity.ts
- src/factories/event.ts
- src/index.ts
- src/services/connection.service.ts
- src/services/inworld_connection.service.ts
- yarn.lock
* Add mute/unmute events support
* Allow to build history transcript inside SDK
* Add parameters to triggers
* Replace checking emotions behavior and strength by direct property access
> Release 1.0.0

- CHANGELOG.md
- __tests__/components/history.spec.ts
- __tests__/components/sound/grpc_audio.playback.spec.ts
- __tests__/connection/web-socket.connection.spec.ts
- __tests__/entities/character.entity.spec.ts
- __tests__/entities/inworld_packet.entity.spec.ts
- __tests__/factories/event.spec.ts
- __tests__/helpers.ts
- __tests__/services/connection.service.spec.ts
- __tests__/services/inworld_connection.service.spec.ts
- examples/chat/src/App.tsx
- src/components/history.ts
- src/components/sound/grpc_audio.playback.ts
- src/connection/web-socket.connection.ts
- src/entities/character.entity.ts
- src/factories/event.ts
- src/services/connection.service.ts
- src/services/inworld_connection.service.ts
Add interrupt method to connection
> Allow to interrupt character manually

- CHANGELOG.md
- src/entities/inworld_packet.entity.ts
> fix: Fix function call that checks its narrated action

- CHANGELOG.md
- __tests__/components/history.spec.ts
- __tests__/components/sound/grpc_audio.playback.spec.ts
- __tests__/connection/web-socket.connection.spec.ts
- __tests__/entities/character.entity.spec.ts
- __tests__/entities/inworld_packet.entity.spec.ts
- __tests__/factories/event.spec.ts
- __tests__/helpers.ts
- __tests__/services/connection.service.spec.ts
- __tests__/services/inworld_connection.service.spec.ts
- examples/chat/src/App.tsx
- package.json
- src/components/history.ts
- src/components/sound/grpc_audio.playback.ts
- src/connection/web-socket.connection.ts
- src/entities/character.entity.ts
- src/entities/inworld_packet.entity.ts
- src/factories/event.ts
- src/services/connection.service.ts
- src/services/inworld_connection.service.ts
* Allow to interrupt character manually
* Replace character getters by direct property access
* Fix function call that checks its narrated action
> Release 1.1.0

- CHANGELOG.md
- __tests__/connection/web-socket.connection.spec.ts
- __tests__/factories/event.spec.ts
- __tests__/helpers.ts
- examples/chat/src/App.tsx
- package.json
- src/components/sound/grpc_audio.playback.ts
- src/connection/web-socket.connection.ts
- src/factories/event.ts
- src/services/connection.service.ts
* Replace CancelResponses by Mutation.CancelResponses on the protocol level
* Send TextEvent before CancelResponses on text interruption
* Continue audio playing after interruption in Safari
> Release 1.2.0

- CHANGELOG.md
- __tests__/clients/inworld.client.spec.ts
- __tests__/components/history.spec.ts
- __tests__/components/sound/grpc_audio.playback.spec.ts
- __tests__/connection/web-socket.connection.spec.ts
- __tests__/data_structures.ts
- __tests__/entities/inworld_packet.entity.spec.ts
- __tests__/factories/event.spec.ts
- __tests__/helpers.ts
- __tests__/services/connection.service.spec.ts
- __tests__/services/inworld_connection.service.spec.ts
- jest.config.json
- package.json
- src/clients/inworld.client.ts
- src/common/data_structures.ts
- src/common/helpers.ts
- src/components/history.ts
- src/components/sound/grpc_audio.playback.ts
- src/components/sound/player.ts
- src/connection/web-socket.connection.ts
- src/entities/inworld_packet.entity.ts
- src/factories/event.ts
- src/index.ts
- src/services/connection.service.ts
- src/services/inworld_connection.service.ts
- src/services/world_engine.service.ts
* Allow to use extended capabilities and scene props
* Allow to send and receive custom proto packet
> Release 1.3.0

- CHANGELOG.md
- package.json
- src/common/helpers.ts
- src/components/sound/inworld_recorder.ts
* Fix audio recording for iOS mobile using LTE
> Release 1.3.1

- CHANGELOG.md
- package.json
- src/components/sound/grpc_web_rtc_loopback_bidi.session.ts
- src/components/sound/inworld_recorder.ts
* Fix audio playback for iOS mobile using LTE
> Release 1.3.2

- CHANGELOG.md
- examples/generate_token/README.md
- examples/generate_token/index.ts
- package.json
* feat: Updating example generate token
> feat: Update example generate token

- RELEASEME.md
* docs: Adding new release documentation
> docs: adding release documentation

- CHANGELOG.md
- package.json
Use correct link to GitHub page
> fix: Use correct link to GitHub page (#41)

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
- .npmignore
- .release-it.json
- CHANGELOG.md
- RELEASEME.md
- package.json
- yarn.lock
The same changes: https://github.com/inworld-ai/inworld-nodejs-sdk/pull/61
> Add release manual workflow

- CHANGELOG.md
- __tests__/helpers.ts
- __tests__/services/connection.service.spec.ts
- __tests__/services/pb/world_engine.service.spec.ts
- examples/chat/src/app/connection.ts
- src/common/data_structures.ts
- src/services/connection.service.ts
- src/services/pb/pb.service.ts
- src/services/pb/world_engine.service.ts
Add `beforeLoadScene` and `afterLoadScene` callbacks
> Feat: Improve extensions

- .github/workflows/release.yml
Reconfigure action to allow push.
> feat(release): allow to push

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/pull_request_template.md
Add GitHub templates for issues (bug and feature) and PR
https://inworldai.atlassian.net/browse/CORE-3782
> chore: Add issues and PR templates

- CHANGELOG.md
- __tests__/components/history.spec.ts
- src/components/history.ts
Wrap narrated actions with asterisks
https://inworldai.atlassian.net/browse/CORE-3622
> feat: Wrap narrated actions with asterisks

- .npmignore
Remove excess files from published package
https://inworldai.atlassian.net/browse/CORE-3832
> chore: Add missed files to .npmignore

- CHANGELOG.md
- __tests__/entities/inworld_packet.entity.spec.ts
- __tests__/services/connection.service.spec.ts
- src/components/history.ts
- src/entities/inworld_packet.entity.ts
Include a correlationId for the overlooked methods.
https://inworldai.atlassian.net/browse/CORE-3933
> Include the correlationId in both the fromProto conversion method and the associated historical items

- .github/actions/build_package/action.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
The same PR is made for Node.js https://github.com/inworld-ai/inworld-nodejs-sdk/pull/81
Improve release process. I.e. splitting release wf to 3 steps:
- GitHub release + tag
- Npm release
- Slack notifications
So it'll be possible to restart `npm publish` step in case of failure
https://inworldai.atlassian.net/browse/CORE-3831
> Slack notifications

- .npmignore
- TESTME.md
- Unit testing
- Manual testing
https://inworldai.atlassian.net/browse/CORE-4129
> Add documentation detailing how to test the package

- examples/chat/package.json
- examples/chat/src/App.tsx
- examples/chat/yarn.lock
Remove excess calls that are now done inside close
https://inworldai.atlassian.net/browse/CORE-4297
> fix: Update close call for example

- CHANGELOG.md
- __tests__/common/helpers.spec.ts
- __tests__/components/history.spec.ts
- __tests__/components/sound/grpc_audio.playback.spec.ts
- __tests__/components/sound/grpc_audio.recorder.spec.ts
- __tests__/components/sound/grpc_web_rtc_loopback_bidi.session.spec.ts
- __tests__/components/sound/inworld_player.spec.ts
- __tests__/components/sound/inworld_recorder.spec.ts
- __tests__/components/sound/player.spec.ts
- __tests__/entities/session_token.entity.spec.ts
- __tests__/guard/number.spec.ts
- __tests__/helpers.ts
- __tests__/mocks/window.mock.ts
- __tests__/services/inworld_connection.service.spec.ts
- src/clients/inworld.client.ts
- src/common/constants.ts
- src/common/helpers.ts
- src/components/history.ts
- src/components/sound/grpc_audio.playback.ts
- src/components/sound/grpc_audio.recorder.ts
- src/factories/event.ts
- src/guard/number.ts
- src/services/connection.service.ts
Improve test coverage. Mostly it's related with DOM objects' mocks
https://inworldai.atlassian.net/browse/CORE-4268
> chore: Improve test coverage

- CHANGELOG.md
- __tests__/services/pb/world_engine.service.spec.ts
- examples/generate_token/yarn.lock
- proto/feedback.pb.ts
- proto/packets.pb.ts
- proto/state_serialization.pb.ts
- proto/world-engine.pb.ts
- src/services/pb/world_engine.service.ts
- tsconfig.json
- yarn.lock
Add a new field “description” into the ClientRequest field and use it to provide more information
Client Description Format: `<SDK Name/SDK Subname>; <SDK Version>; <OS or Container>; <Client Name>`.
https://inworldai.atlassian.net/browse/CORE-4189
> feat: Improve client request format

- examples/chat/src/app/chat/Chat.tsx
See description inside issue
https://github.com/inworld-ai/inworld-web-sdk/issues/89
TODO: Add Jira ticket
> fix: Control recording state more carefully in chat example

- CHANGELOG.md
- __tests__/components/sound/grpc_audio.playback.spec.ts
- __tests__/connection/web-socket.connection.spec.ts
- __tests__/entities/continuation/session_continuation.entity.spec.ts
- __tests__/entities/emotion_behavior.entity.spec.ts
- __tests__/entities/emotion_strength.entity.spec.ts
- __tests__/factories/event.spec.ts
- __tests__/helpers.ts
- __tests__/services/connection.service.spec.ts
- __tests__/services/inworld_connection.service.spec.ts
- __tests__/services/pb/state_serialization.service.spec.ts
- __tests__/services/pb/world_engine.service.spec.ts
- proto/ai/inworld/engine/v1/feedback.pb.ts
- proto/ai/inworld/engine/v1/state_serialization.pb.ts
- proto/ai/inworld/engine/world-engine.pb.ts
- proto/ai/inworld/packets/packets.pb.ts
- src/clients/inworld.client.ts
- src/common/data_structures.ts
- src/connection/web-socket.connection.ts
- src/entities/continuation/previous_dialog.entity.ts
- src/entities/emotion_behavior.entity.ts
- src/entities/emotion_strength.entity.ts
- src/entities/inworld_packet.entity.ts
- src/factories/event.ts
- src/index.ts
- src/services/connection.service.ts
- src/services/inworld_connection.service.ts
- src/services/pb/state_serialization.service.ts
- src/services/pb/world_engine.service.ts
Proto files structure was changed
https://inworldai.atlassian.net/browse/CORE-4633
> feat: Update proto to new structure

- .github/workflows/release.yml
- README_DEV.md
- packages/web-core/package.json
> fix(web-core): Run npm-release and  release-notification using WS commands

- examples/chat/package.json
- examples/chat/src/App.tsx
- examples/chat/src/app/chat/Chat.tsx
- examples/chat/src/app/chat/History.tsx
- examples/chat/src/app/components/3dAvatar/Animation.tsx
- examples/chat/src/app/components/3dAvatar/Avatar.tsx
- examples/chat/src/app/components/3dAvatar/InworldChar3D.tsx
- examples/chat/src/app/components/3dAvatar/Lipsync.tsx
- examples/chat/src/app/components/3dAvatar/Model.tsx
- examples/chat/src/app/components/3dAvatar/PhonemDataToVisemeDataConverter.ts
- examples/chat/src/app/components/innequin/Innequin.tsx
- examples/chat/src/app/components/innequin/Model.tsx
- examples/chat/src/app/components/innequin/Scene.tsx
- examples/chat/src/app/components/innequin/animator/Animator.tsx
- examples/chat/src/app/components/innequin/animator/facial/Eye.tsx
- examples/chat/src/app/components/innequin/animator/facial/Facial.tsx
- examples/chat/src/app/components/innequin/animator/facial/Mouth.tsx
- examples/chat/src/app/components/innequin/animator/facial/PhonemesToViseme.ts
- examples/chat/src/app/connection.ts
- examples/chat/src/app/helpers/emoji.ts
- examples/chat/src/app/helpers/transform.ts
- examples/chat/src/app/types.ts
- examples/chat/src/defaults.ts
- examples/chat/yarn.lock
Update dependencies and all imports for chat example
> chore(example): Switch to web-core package

- LICENSE.md
- packages/web-core/CHANGELOG.md
Update LICENSE
https://inworldai.atlassian.net/browse/INTG-904
> chore: Update LICENSE.md

- packages/web-core/CHANGELOG.md
- packages/web-core/__tests__/components/history.spec.ts
- packages/web-core/__tests__/services/connection.service.spec.ts
- packages/web-core/package.json
- packages/web-core/src/clients/inworld.client.ts
- packages/web-core/src/components/history.ts
- packages/web-core/src/services/connection.service.ts
Add diff
https://inworldai.atlassian.net/browse/INTG-334
> feat: Add `diff` to the `onHistoryChange` callback as the second parameter

- packages/web-core/CHANGELOG.md
- packages/web-core/replacers/json.cjs
- packages/web-core/src/services/pb/world_engine.service.ts
Also need to replace require by import and export version directly
https://inworldai.atlassian.net/browse/INTG-887
https://github.com/inworld-ai/inworld-web-sdk/issues/100
> fix: Fix esm package building

- .github/actions/build_package/action.yml
- .github/workflows/build.yml
- yarn.lock
Working directory should be clean because it's required for Release action
https://inworldai.atlassian.net/browse/INTG-923
> fix: Ensure working directory is clean

- packages/web-core/CHANGELOG.md
- packages/web-core/__tests__/components/history.spec.ts
- packages/web-core/__tests__/factories/event.spec.ts
- packages/web-core/__tests__/services/inworld_connection.service.spec.ts
- packages/web-core/proto/ai/inworld/engine/world-engine.pb.ts
- packages/web-core/proto/ai/inworld/packets/packets.pb.ts
- packages/web-core/src/components/history.ts
- packages/web-core/src/factories/event.ts
- packages/web-core/src/services/connection.service.ts
- packages/web-core/src/services/inworld_connection.service.ts
Add new event: Outgoing narrated action
Incoming one is already supported
https://inworldai.atlassian.net/browse/INTG-877
> feat: Outgoing narrated actions support

- examples/chat/package.json
- examples/chat/src/app/chat/Chat.tsx
- examples/chat/yarn.lock
- package.json
Add action to example
https://inworldai.atlassian.net/browse/INTG-877
> feat: Narrated actions example

- packages/web-core/CHANGELOG.md
- packages/web-core/src/components/history.ts
Added missed character object to history item
https://inworldai.atlassian.net/browse/INTG-1144
> fix: Fix copy history transcript action

- packages/web-core/CHANGELOG.md
- packages/web-core/__tests__/factories/event.spec.ts
- packages/web-core/src/entities/inworld_packet.entity.ts
- packages/web-core/src/factories/event.ts
Fix error sending packets
https://inworldai.atlassian.net/browse/CORE-5675
> fix: Use `targets` property only for multi characters mode

- packages/web-core/CHANGELOG.md
- packages/web-core/__tests__/components/sound/grpc_audio.playback.spec.ts
- packages/web-core/src/components/sound/grpc_audio.playback.ts
Need to use default stop props is they are not provided
https://inworldai.atlassian.net/browse/INTG-1377
> fix: Fix playback props initialization

- examples/chat/src/app/components/innequin/animator/facial/Eye.tsx
- examples/innequin-react/package.json
- examples/innequin-react/yarn.lock
- examples/rpm-react/package.json
- examples/rpm-react/yarn.lock
- packages/web-core/src/components/history.ts
- packages/web-core/src/entities/continuation/previous_dialog.entity.ts
- packages/web-core/src/entities/packets/audio.entity.ts
- packages/web-core/src/factories/event.ts
- packages/web-core/src/services/connection.service.ts
- packages/web-threejs/src/innequin/animator/facial/InnequinEyes.ts
Updated example projects to web-threejs 1.4.0 package
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [x ] I have made corresponding changes to the documentation
> chore: updated Innequin RPM example projects to web-threejs 1.4.0

- packages/web-core/__tests__/components/history.spec.ts
- packages/web-core/__tests__/entities/scene.entity.spec.ts
- packages/web-core/__tests__/services/inworld_connection.service.spec.ts
- packages/web-core/src/components/history.ts
- packages/web-core/src/components/sound/grpc_audio.playback.ts
- packages/web-core/src/entities/scene.entity.ts
- packages/web-core/src/services/connection.service.ts
- Take into account multiple target history
- Improve history displaying
https://inworldai.atlassian.net/browse/FE-464
https://inworldai.atlassian.net/browse/FE-431
> Fe 431 web sdk package version upgrade multi chat issues

- examples/chat/src/App.tsx
- examples/chat/src/app/chat/AdditionalActions.tsx
- examples/chat/src/app/chat/Chat.tsx
- examples/chat/src/app/chat/History.tsx
- examples/chat/src/app/components/CircularRpmAvatar.tsx
Need to move examples changes to separate PR
https://inworldai.atlassian.net/browse/INTG-1262
> example: Allow to change scene and add characters

- packages/web-core/CHANGELOG.md
- packages/web-core/EXTENSIONS.md
- packages/web-core/__tests__/connection/web-socket.connection.spec.ts
- packages/web-core/__tests__/entities/inworld_packet.entity.spec.ts
- packages/web-core/__tests__/entities/scene.entity.spec.ts
- packages/web-core/__tests__/factories/event.spec.ts
- packages/web-core/__tests__/helpers/extension.ts
- packages/web-core/__tests__/helpers/scene.ts
- packages/web-core/__tests__/services/connection.service.spec.ts
- packages/web-core/__tests__/services/conversation.service.spec.ts
- packages/web-core/__tests__/services/inworld_connection.service.spec.ts
- packages/web-core/src/common/data_structures.ts
- packages/web-core/src/components/history.ts
- packages/web-core/src/connection/web-socket.connection.ts
- packages/web-core/src/entities/packets/inworld_packet.entity.ts
- packages/web-core/src/entities/scene.entity.ts
- packages/web-core/src/factories/event.ts
- packages/web-core/src/services/connection.service.ts
- packages/web-core/src/services/inworld_connection.service.ts
https://inworldai.atlassian.net/browse/INTG-1589
> feat: Support new runtime protocol session configuration

- README.md
https://inworldai.atlassian.net/browse/INTG-1783
> feat: Add links to 3D examples to README.md

- .github/workflows/release.yml
- .yarnrc.yml
- yarn.lock
> fix: Fix release action

- examples/chat/src/app/connection.ts
- packages/web-core/CHANGELOG.md
- packages/web-core/__tests__/components/history.spec.ts
- packages/web-core/__tests__/entities/scene.entity.spec.ts
- packages/web-core/src/common/data_structures.ts
- packages/web-core/src/components/history.ts
- packages/web-core/src/entities/scene.entity.ts
- packages/web-core/src/services/connection.service.ts
https://inworldai.atlassian.net/browse/INTG-1931
> fix: Add characters that are out of scene to historical packets

- .github/actions/build_package/action.yml
- .github/actions/upload_minified_version/action.yml
- .github/workflows/minify.yml
- .github/workflows/release.yml
- packages/web-core/tsconfig.json
https://inworldai.atlassian.net/browse/INTG-1569
> fix: Fix minify action

- TESTME.md
https://inworldai.atlassian.net/browse/INTG-1865
> docs: Improve TESTME.md description

- .github/workflows/release.yml
- RELEASEME.md
- packages/web-core/.npmignore
- packages/web-core/.release-it.prerelease.json
- packages/web-threejs/.npmignore
- packages/web-threejs/.release-it.prerelease.json
> chore: Beta version publishing

- examples/chat/package.json
- examples/chat/src/app/chat/Chat.tsx
- examples/chat/src/app/chat/RecorderActions.tsx
- examples/chat/yarn.lock
- examples/generate_token/package.json
- examples/generate_token/yarn.lock
- packages/web-core/CHANGELOG.md
EXAMPLE
https://inworldai.atlassian.net/browse/INTG-1886
> example: Support SPEECH_RECOGNITION_ONLY mode

- packages/web-core/package.json
- packages/web-core/src/factories/event.ts
Fix latency formatting
https://inworldai.atlassian.net/browse/INTG-2147
> fix: Format latency duration to fixed 9 digits after decimal point

- packages/web-core/CHANGELOG.md
- packages/web-core/src/components/history.ts
feat: adding S2C logs to conversation history
> feat: adding S2C logs to conversation history

- packages/web-core/CHANGELOG.md
> fix: Fix CHANGELOG

- packages/web-core/__tests__/services/connection.service.spec.ts
> feat: start of ping pong test

- packages/web-core/src/index.ts
- packages/web-threejs/src/index.ts
https://inworldai.atlassian.net/browse/INTG-2397
> chore: Change 2024 to 2025 in copyright terms

- packages/web-core/CHANGELOG.md
- packages/web-core/package.json
- packages/web-core/src/services/connection.service.ts
Need to use capabilities converted to proto on scene update
https://inworldai.atlassian.net/browse/INTG-2671
> fix: Fix changing of scene capabilities
